context:
  version: "6.1.0"

package:
  name: jasmine-npm
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/jasmine/-/jasmine-${{ version }}.tgz
  sha256: 8baf7322d5d7c206075b7fa4f8a068c06898b5a60625432156f09d634919c756

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - jasmine help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: CLI for Jasmine, a simple JavaScript testing framework for browsers and Node
  homepage: https://github.com/jasmine/jasmine-npm
  repository: https://github.com/jasmine/jasmine-npm

extra:
  recipe-maintainers:
    - danielnachun
