context:
  version: "5.9.0"

package:
  name: jasmine-npm
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/jasmine/-/jasmine-${{ version }}.tgz
  sha256: aa6caa932c9985195b15ed74d0a8a50af28f4122399653ea5323a43e90d97bc0

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - jasmine help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: CLI for Jasmine, a simple JavaScript testing framework for browsers and Node
  homepage: https://github.com/jasmine/jasmine-npm
  repository: https://github.com/jasmine/jasmine-npm

extra:
  recipe-maintainers:
    - danielnachun
